/**
 * AUTO-GENERATED by tools/slop-trainer/fit.py. DO NOT EDIT BY HAND.
 * Generated: 2026-05-23T07:08:02.758628+00:00
 * Corpus: 643 human / 531 llm
 * Held-out AUC: 0.890  (kill threshold 0.7)
 * Mode: synthetic
 *
 * 'synthetic'  -> normal synthetic-text-likelihood framing, thresholds [0.50,0.70,0.85]
 * 'boilerplate'-> AUC below kill threshold; degraded high-precision framing,
 *                 only the top ~5% of posts score above 0.
 */

export type SlopMode = "synthetic" | "boilerplate";

export const SLOP_MODE: SlopMode = "synthetic";

/** Probability breakpoints for the 0..3 bucket mapping. */
export const SLOP_DECISION_THRESHOLDS: readonly [number, number, number] = [0.5, 0.7, 0.85] as const;

export const SLOP_WEIGHTS = {
  bias: 1.408920,
  invSentenceLengthVariance: 1.804813,
  fingerprintRate: -0.084747,
  hedgeRate: -0.142556,
  emDashRate: 0.505234,
  oxfordRate: 1.379791,
  invTypeTokenRatio: -4.777508,
  invOpenerDiversity: 0.617831,
  invQuestionRate: -0.508190,
  profanityRate: -1.376007,
} as const;
