/**
 * AUTO-GENERATED by tools/slop-trainer/fit.py. DO NOT EDIT BY HAND.
 * Generated: 2026-05-21T06:54:06.330347+00:00
 * Corpus: 150 human / 150 llm
 * Held-out AUC: 1.000  (kill threshold 0.7)
 * Mode: synthetic
 *
 * 'synthetic'  -> normal synthetic-text-likelihood framing, thresholds [0.50,0.70,0.85]
 * 'boilerplate'-> AUC below kill threshold; degraded high-precision framing,
 *                 only the top ~5% of posts score above 0.
 */

export type SlopMode = "synthetic" | "boilerplate";

export const SLOP_MODE: SlopMode = "synthetic";

/** Probability breakpoints for the 0..3 bucket mapping. */
export const SLOP_DECISION_THRESHOLDS: readonly [number, number, number] = [0.5, 0.7, 0.85] as const;

export const SLOP_WEIGHTS = {
  bias: -24.044451,
  invSentenceLengthVariance: 18.355139,
  fingerprintRate: 0.325941,
  hedgeRate: 0.469957,
  emDashRate: 0.000000,
  oxfordRate: 0.000000,
  invTypeTokenRatio: 4.167143,
  invOpenerDiversity: -1.676867,
  invQuestionRate: 4.203045,
  profanityRate: -0.327232,
} as const;
